Repository VTPDevelopment/Silk, pull requests merged in 2021-08, with the labels that each got.

#349 Plugin Support!
  Silk.sln
  plugins/TestPlugin/TestPlugin.csproj
  src/Silk.Core/Main.cs
  src/Silk.Core/Services/Bot/PluginLoaderService.cs
  src/Silk.Core/Silk.Core.csproj
  src/Silk.Core/Startup.cs
  src/Silk.Core/Utilities/Bot/PluginLoader.cs
Labels: Enhancement, Priority: NORMAL

#364 Add Directory.Build.(props|targets) to solution
  Directory.Build.props
  Directory.Build.targets
  Silk.sln
  plugins/PluginHelper/PluginHelper.csproj
  plugins/RoleMenuPlugin/RoleMenuPlugin.csproj
  src/Silk.Core.Data/Silk.Core.Data.csproj
  src/Silk.Core/Silk.Core.csproj
  src/Silk.Extensions/Silk.Extensions.csproj
  src/Silk.Shared/Silk.Shared.csproj
  tests/Silk.Benchmarks/Silk.Benchmarks.csproj
  tests/Silk.Core.Data.Tests/Silk.Core.Data.Tests.csproj
  tests/Silk.Core.Tests/Services/ConfigServiceTests.cs
  tests/Silk.Core.Tests/Silk.Core.Tests.csproj
  tests/Silk.Core.Tests/Types/AsyncTimerTest.cs
  tests/Silk.Extensions.Tests/Silk.Extensions.Tests.csproj
Labels: Enhancement, Considered

#372 ci(Mergify): configuration update
  .mergify.yml
Labels: Enhancement
